apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-12-13T17:37:41Z"
  generation: 1
  labels:
    k8s-app: nginx-app
  name: nginx-app
  namespace: default
  resourceVersion: "848"
  uid: c857a53d-70e5-441f-a60c-6323e27b9227
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: nginx-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: nginx-app
      name: nginx-app
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx-app
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-12-13T17:38:24Z"
    lastUpdateTime: "2021-12-13T17:38:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-12-13T17:37:41Z"
    lastUpdateTime: "2021-12-13T17:38:24Z"
    message: ReplicaSet "nginx-app-c7d845577" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
